import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'

export default function layout({ children}) {
  return (
    <>
      <Head>
        <title>Crew Labs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
        <main>{children}</main>
      <Footer />
    </>
  )
}
